
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Vincenzo",
    "number": "123-456789"
}

###
DELETE http://localhost:3001/api/persons/692231ab4fa69fd0af2cbd2f

###
GET http://localhost:3001/api/persons